//           LOGIN             
//     nome:                     
//     senha:                    
//        | SUBMIT | -> botão para receber as entradas        
//    | MUDAR SENHA | -> botão que abre uma nova janela de "Mudar Senha"
//    | CRIAR REGISTRO | -> botão que abre uma nova janela de "Criar Registro"
//    | EXCLUIR CONTA | -> botão que abre uma nova janela de "Excluir Conta"



//          MUDAR SENHA
//    nome:
//    senha atual:
//    senha nova: 
//                 | SUBMIT |  -> botão para receber as entradas
//    | LOGIN | -> botão que fecha a janela atual e abre uma nova janela de "Login"
//    | CRIAR REGISTRO | -> botão que fecha a janela atual e abre uma nova janela de "Criar Registro"
//    | EXCLUIR CONTA | -> botão que fecha a janela atual e abre uma nova janela de "Excluir Conta"



//         CRIAR REGISTRO
//    nome:
//    senha:
//            | SUBMIT |  -> botão para receber as entradas
//    | MUDAR SENHA | -> botão que fecha a janela atual e abre uma nova janela de "Mudar Senha"
//    | LOGIN | -> botão que fecha a janela atual e abre uma nova janela de "Login"
//    | EXCLUIR CONTA | -> botão que fecha a janela atual e abre uma nova janela de "Excluir Conta"




//         EXCLUIR CONTA
//    nome:
//    senha:
//            | SUBMIT |  -> botão para receber as entradas
//    | MUDAR SENHA | -> botão que fecha a janela atual e abre uma nova janela de "Mudar Senha"
//    | LOGIN | -> botão que fecha a janela atual e abre uma nova janela de "Login"
//    | CRIAR REGISTRO | -> botão que fecha a janela atual e abre uma nova janela de "Criar Registro"




//                                        MENU PRINCIPAL
//
//
//                                         NOME_USUARIO 
//
//
//                                     | MUDAR BACKGROUND |
//
//  ____________________________________________________________________________________________________
//  |                                                                                                  |
//  |                                          MENU TAREFAS                                            |
//  |                                                                                                  |
//  |  TAREFA G       | CONCLUIDO|    | REMOVER TAREFA |  |EDITAR TAREFA|   | VER DETALHES DA TAREFA|  |
//  |  TAREFA D       | CONCLUIDO|    | REMOVER TAREFA |  |EDITAR TAREFA|   | VER DETALHES DA TAREFA|  |
//  |  TAREFA A       | CONCLUIDO|    | REMOVER TAREFA |  |EDITAR TAREFA|   | VER DETALHES DA TAREFA|  |
//  |  TAREFA B       | CONCLUIDO|    | REMOVER TAREFA |  |EDITAR TAREFA|   | VER DETALHES DA TAREFA|  |
//  |  TAREFA C       | CONCLUIDO|    | REMOVER TAREFA |  |EDITAR TAREFA|   | VER DETALHES DA TAREFA|  |
//  |                                                                                                  | 
//  |                 | PAG 1 |    | PAG 2 |   | PAG 3 |    | PAG 4 |                                  |
//  |__________________________________________________________________________________________________|
//
//   | 22% CONC | 
// 
//   | ADICIONAR TAREFA |  | LIMPAR TUDO |   | LIMPAR CONCLUÍDAS |

// OBS:
// | CONCLUIDO | -> botão que serve para concluir uma tarefa
// | ADICIONAR TAREFA | -> abre uma nova janela de "Adicionar Tarefa"
// | REMOVER TAREFA | -> botão que apaga a tarefa escolhida
// | EDITAR TAREFA  | -> abre uma nova janela de "Editar Tarefa"
// | VER DETALHES DA TAREFA | -> abre uma nova janela de "Ver Detalhes da Tarefa"
// | PAG 1 | -> botão que reinicia MENU TAREFAS para a página 1
// | PAG 2 | -> botão que reinicia MENU TAREFAS para a página 2
// | PAG 3 | -> botão que reinicia MENU TAREFAS para a página 3
// | PAG 4 | -> botão que reinicia MENU TAREFAS para a página 4


//              ADICIONAR TAREFA
//  TITULO :
//         | SUBMIT |
//  | VOLTAR | -> botão para voltar à tela de "MENU PRINCIPAL" 


//                 EDITAR TAREFA
//  TITULO :
//  PRIORIDADE:
//  DESCRIÇÃO:
//  HORA:
//  DATA:
//         | SUBMIT |
//  | VOLTAR | -> botão para voltar à tela de "MENU PRINCIPAL"


//                 Ver Detalhes da Tarefa
//  TITULO :
//  <titulo>
//  PRIORIDADE: 
//  <prioridade>
//  DESCRIÇÃO:
//  <descrição>
//  HORA:
//  <hora>
//  DATA:
//  <data:
//  CONCLUÍDO: 
//  <conclusão>
//  | VOLTAR | -> botão para voltar à tela de "MENU PRINCIPAL"